# Generated by Django 2.2 on 2019-06-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
    ]
